---
title: "test"
format: pptx
editor: visual
---

```{r}
# run this code - won't appear in prez
#| message: false
#| warning: false
#| include: false

#  uncomment this if you haven't installed aRtsy yet, otherwise leave commented out
#install.packages("aRtsy") 

library(aRtsy)
library(ggplot2)
```

## EXAMPLE

Here's a simple example

```{r}
# Let's say "Hello World" in an artistic way using an algorithmically generated manner!
set.seed(1234) #choose whatever number you want

# make your personalized card 
# choose from a large number of options! https://github.com/koenderks/aRtsy/tree/development
EXAMPLE <- canvas_blacklight(
  colors = colorPalette("tuscany1"), #choose your palette
  resolution = 300 #keep this at 300!
  ) +
  ggtitle("EXAMPLE") +
  theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 24)) # keep this for nice formatting

EXAMPLE
```

## Scott Coffin

Here's my contribution

```{r, eval=FALSE}
# Let's say "Hello World" in an artistic way using an algorithmically generated manner!
set.seed(95605) #choose whatever number you want. I chose my zip code

# make your personalized card 
# choose from a large number of options! https://github.com/koenderks/aRtsy/tree/development
scott <- canvas_chladni( #replace your name
  #choose a palette 
  #colors = colorPalette("tuscany1"),  #default
  # See options with ?colorPallete. Or choose whatever colors you want with names/hex codes/other packages!
  colors = calecopal::cal_palette("superbloom3", n = 5),
  waves = 5,
  warp = 0.4,
  angles = "perlin",
  distances = "perlin",
  resolution = 300) + #keep this at 300 to reduce render time
  ggtitle("Scott Coffin") + # type your name here
  theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 24)) # keep this for nice formatting

scott
```

**Paint smoke**

You can simply replace the following with your personalized selections

```{r smoke}
# Let's say "Hello World" in an artistic way using an algorithmically generated manner!
#set.seed() #choose whatever number you want. I chose my zip code

# make your personalized card 
# choose your function -> https://github.com/koenderks/aRtsy/tree/development
set.seed(760)
mysmoke <- canvas_smoke(
  colors = colorPalette("random", n=600),# replace with your actual function
#yourcolorshere
  resolution = 300) + #keep this at 300 to reduce render time
  ggtitle("Smoke") + # type your name here
  theme(plot.title = element_text(hjust = 0.2, face = "bold", size = 16)) # keep this for nice formatting

mysmoke
# once you're happy with your selection, place your name in the ggarrange below
# then save -> stage -> commit -> pull -> push!
```

## Our Mosaic

```{r}
ggpubr::ggarrange(EXAMPLE,
                  mystroke
                  )
```
